# Generated by Django 4.1.3 on 2022-12-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
            ],
        ),
        migrations.RemoveField(
            model_name="chatuser",
            name="rooms",
        ),
        migrations.RemoveField(
            model_name="chatuser",
            name="user",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="room",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="user",
        ),
        migrations.DeleteModel(
            name="ChatRoom",
        ),
        migrations.DeleteModel(
            name="ChatUser",
        ),
        migrations.DeleteModel(
            name="Membership",
        ),
    ]
