# Generated by Django 4.1.3 on 2022-12-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vnz", "0002_alter_educator_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="educator",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="educator_photos"),
        ),
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="student_photos"),
        ),
    ]
