# Generated by Django 4.1.3 on 2022-12-16 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vnz", "0003_educator_photo_student_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="group",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="vnz.groups"
            ),
        ),
    ]
