# Generated by Django 4.1.3 on 2022-12-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vnz", "0004_student_group"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ListOfStudentPerGroup",
        ),
    ]
