# Generated by Django 4.1.3 on 2022-12-16 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vnz", "0005_delete_listofstudentpergroup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="group",
        ),
    ]
