# Generated by Django 4.1.3 on 2022-12-19 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vnz", "0006_remove_test_group"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
