# Generated by Django 4.1.3 on 2022-12-20 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vnz", "0009_preferences_preferences_one entry per user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Preferences",
        ),
    ]
