# Generated by Django 4.1.3 on 2022-12-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vnz", "0010_delete_preferences"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
